# Generated by Django 3.0.8 on 2020-08-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='users_likes',
            new_name='users_like',
        ),
    ]
