# Generated by Django 3.0.8 on 2020-08-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20200801_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
