version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=_faq4of+#7_y-0ga4i04&g#qqs1-)o!fud4)_5w7gv+rm+a^vf
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  # postgres:
  #   image: your/postgres
  #   volumes:
  #     - pgsql-data:/var/lib/pgsql
